#!/bin/bash

while :
	do
		echo "1)Insert\n2)Delete\n3)Search"
		read choice
		case $choice in
		1)
			echo "Rollno,name,sem,Marks1,marks2,marks3"
			read a b c d e f
			if [ -e record.txt ]
			then
				echo "$a,$b,$c,$d,$e,$f">>record.txt
			else
				touch record.txt
				chmod 777 record.txt	
			fi
			;;
		2)
			echo "Delete"
			;;
		3)
			read g
			echo "Matched records are as follows"
			grep -n  $g record.txt 
			;;
		*)
			break
		esac
	done

